### ISSUE TITLE
How to use the Read More module?

### ISSUE THREAD

**Issue by kshiteesh** [mmistakes/hpstr-jekyll-theme#105]
I was wondering how to use the "Read More" module located in `_includes/read-more.html`. From what I gathered it will produce a "Continue Reading" button after showing say, a paragraph on the main page. Clicking on the said button would take the user to the page of the actual post. Am I right? If so, how do I include this feature?

Thanks!

**Comment by mmistakes** [comment]
That module is for "related posts". It appears on a post page after the main content and comments sections. If there is more than one related post it displays the module. 

If you want to do a "continue reading" button on the archive pages you'll need to modify the layout some to use `{{ post.excerpt }}` instead of `{{ post.content }}`. See #47 for more guidance.
