### ISSUE TITLE
Blog post samples

### ISSUE THREAD

**Issue by vishaleckhart** [mmistakes/hpstr-jekyll-theme#106]
Thanks for your contribution.  It was a relief to find such a complete yet simple fork to configure.  The only issue I have is finding out how to show the post title and a sample instead of the whole post.
Any ideas?  Keep up the good work!
vishal

**Comment by mmistakes** [comment]
You're welcome.

Check out issue #47 for info on how to use a short description for each post instead of the whole thing. You essentially modify homepage to use `{{ post.excerpt }}` instead. Then you can write unique excerpts for each post, put that in the YAML Front Matter and it will display. Or if you're lazy you can have Jekyll truncate the posts for you.

**Comment by vishaleckhart** [comment]
do I place the |{{ post.excerpt }} in the config.yml or in some other 
file?  I can't find where it says ||{{ post.excerpt }} in order to 
replace it.
thank you
|

**Comment by mmistakes** [comment]
It's in the [`index.html`](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/index.html#L38) file in the root of your site.

**Comment by huizache** [comment]
Vishal, once index.html edited, you can add to the  YAML Front Matter:
excerpt: your teaser text without any mardown.

Thanks for suggesting mmistakes to me, it works very well.

**Comment by neelambar** [comment]
Hi,
is there any way to correctly display reading time (based on complete post content) on the index.html when using excerpt ?

Thanks.
