### ISSUE TITLE
Change /pageX to /page/X

### ISSUE THREAD

**Issue by aleksandar-todorovic** [mmistakes/hpstr-jekyll-theme#110]
Okay, so I'm using this theme and I noticed an issue that can't be easily fixed without changing the theme.

Currently, the archive links are listed as `/pageX` which I think should be changed to `/page/X`.

The reason why I'm suggesting this is to have a simple way to block the access of crawlers to those pages. It's much easier to include `Disallow: /page/` than to create a new row for every single one of those links.

Here's the current list of Google's search results when I search for `site:r3bl.me` to prove that is a problem:

![screenshot from 2015-08-16 00 41 52](https://cloud.githubusercontent.com/assets/4890548/9291112/d5b67f88-43af-11e5-8c35-ffe8f7adb1ad.png)

**Comment by mmistakes** [comment]
This is untested but you could try altering the path by adding this line to your `_config.yml`. If you need more info on how it works check the official [pagination Jekyll docs](http://jekyllrb.com/docs/pagination/#enable-pagination). This [blog post](http://www.ericlagergren.com/blog/jekyll-pagination/) may help you as well.

```
paginate_path: "/page/:num/"
```

Pagination is likely going to be [an issue with Jekyll 3](https://talk.jekyllrb.com/t/announcement-retiring-jekyll-paginate/1004) anyways since support for it is being dropped. So I don't want to spend too much time on it if it's going away anyways. I don't personally use pagination on any of my sites because it's never really worked all that well or done things like paginate categories without a ton of hacky work arounds.

Another thing you could do is add a Liquid conditional to `head.html` that would allow you to add or enable `<meta name="robots" content="noindex">` to the `index.html` pages in `/pageX/` to let search engines not to index them.

Also. Have you tried doing `Disallow: /page` in your `robots.txt` file? In my quick test it seems to block `/page2/`, /page3/`, /pageWhatever/` just fine without you having to manually disallow all of them.

![screen shot 2015-08-16 at 12 31 16 am](https://cloud.githubusercontent.com/assets/1376749/9291991/22577330-43ae-11e5-88be-d588880bab48.png)

**Comment by aleksandar-todorovic** [comment]
> Also. Have you tried doing `Disallow: /page` in your robots.txt file? In my quick test it seems to block `/page2/`, `/page3/`, `/pageWhatever/` just fine without you having to manually disallow all of them.

I'm trying it out now (I pushed the change last night), but I'm guessing that it would take a while for Google to fix its results. Judging by Google's robots.txt Tester, it seems like this works.

I'm guessing that GitHub won't remove the support for the pagination for quite a while since there are so many sites depending on it, so I'm going to assume that I shouldn't be too worried about this at the moment and that this line in robots.txt is everything I need at the moment.

Thanks for the tip!

**Comment by mmistakes** [comment]
Yeah it could take Google some time to re-index and apply the changes.
Especially if it's a small site. If you've setup everything in Google
Webmaster tools you may be able to push that along and request those pages
be removed from SERPs.

**Comment by aleksandar-todorovic** [comment]
I managed to make a progress (Google still indexes some of them, but they are hidden in the search results) using webmaster tools. Not sure if you feel like changing `/pageX` to `/page/X` so I'm gonna leave this issue open and let you decide on what to do with it.

**Comment by mmistakes** [comment]
Closing to avoid breaking sites. The fix of changing `paginate_path` in `_config.yml` to something else is easy enough that I don't think it needs to be dictated by the theme.
