### ISSUE TITLE
site not using 100% width on iPhone 6S

### ISSUE THREAD

**Issue by dgoppenheimer** [mmistakes/hpstr-jekyll-theme#122]
First, thank you for a fantastic theme with clear installation and use instructions!

I built a site using a fork of HPSTR and it looks great on the desktop, iPad, and iPhone in landscape. However, in portrait position, there is about 1/3 of screen width that is blank. See image below. It resizes just fine when you re-orient the phone to landscape, but will not resize properly in portrait. Where do I begin to try to fix this? I poked around the web and it was suggested that I add `body { min-width: 980px }` to `body` in the css somewhere. Where should I begin modifying the css? 

![hpstr-theme-iphone6s](https://cloud.githubusercontent.com/assets/2947157/11016826/3fc23944-855a-11e5-8223-a4563c51e9e4.jpg)

**Comment by mmistakes** [comment]
The problem is the long code blocks in your posts. If you scroll down about half way in your first post and look at the `~Library/Application Support/` line you'll see what I mean. 

Code blocks have styling set on them to not wrap lines, which is causing is long string of text to extend outside of its parent container and push everything else outside the viewport. 

You could remove `white-space: nowrap;` from it in the CSS but that will likely break something else.
The quick fix would be to not do such long inline code blocks and use the {% highlight %}{% endhighlight %} instead, which isn't ideal for single lines but it will make it a block element with scroll bars to avoid pushing everything else around.

**Comment by dgoppenheimer** [comment]
I changed the long single code blocks to the {% highlight %}{% endhighlight %} from the back tics and that cured the problem. Man, you are a friggin' genius! Thank you so very much! Mark this as solved.
