### ISSUE TITLE
Modify template so as display a "show-more" button instead of the whole blog post

### ISSUE THREAD

**Issue by prodicus** [mmistakes/hpstr-jekyll-theme#124]
Hey mmistakes, 

I was wondering how should I edit the template so as to display 
- The blog post title
- It's description
- and 3-4 lines of the content
- and a show more button which would expand it to the full blog post.

I am new to web-dev and couldn't understand the workings of the template. Any help here would be deeply appreciated.

By the way, Great work with the theme, looks awesome and by far the best jekyll theme I have tried! :) :+1:

**Comment by mmistakes** [comment]
Hello. Check #47 for a starting point. Basically instead of displaying the entire content of a post with `{{ post.content }}` you use `{{ post.excerpt }}` instead. Jekyll can do [automatic excerpts](http://jekyllrb.com/docs/posts/#post-excerpts) that you can cut using a read more tag (similar to how Wordpress does it).

I personally like more control so in each of my posts I have `excerpt:` in the YAML Front Matter and write a unique excerpt to display instead. I do this on [my personal site](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/_layouts/archive.html) which you can check out here if you want more ideas.

**Comment by prodicus** [comment]
Many thanks. Achieved it by doing the following changes in [index.html](https://github.com/prodicus/prodicus.github.io/blob/master/index.html#L38)

Cheers.

**Comment by mmistakes** [comment]
All of that can be changed, just a matter of how comfortable you are with CSS. I'd suggest using the web developer tools in any modern browser, inspect the element you want to change to see what the class name is and then apply the change in appropriate SCSS partials.
