### ISSUE TITLE
Adding unique captions for each image in the figure tag

### ISSUE THREAD

**Issue by saatvikshah1994** [mmistakes/hpstr-jekyll-theme#133]
Following your documentation [here](https://mmistakes.github.io/hpstr-jekyll-theme/sample-post-images/), I was able to get multiple images to be placed side by side. However, instead of providing a single caption for the entire set of images, I would like to add a unique caption for each image.

I tried writing raw html as:
```
<table align="center">
<tr align="center">
<td style="padding:5px;" align="center"><div class="container" align="center">
<a href="{{ site.baseurl }}/images/a1.png"><img src="{{ site.baseurl }}/images/a1.png" alt="" height="200px" width="400px"/></a>
<h5 align="center">Tag 1</h5>
</div>
</td>
<td style="padding:5px;">
<div class="container" align="center">
<a href="{{ site.baseurl }}/images/a2.png"><img src="{{ site.baseurl }}/images/a2.png" alt="" height="200px" width="400px"/>
</a>
<h5 align="center">Tag 2</h5>
</div>
</td>
</tr>
</table>
```

However, I noticed that images are being rendered in different sizes then on Chrome and Firefox.

How do you suggest I go about it?

**Comment by mmistakes** [comment]
You'll have to tinker with the CSS since the theme doesn't support this. I'd also ditch the `<table>` markup since that's generally a bad idea for layout.

Instead maybe start with something like this:

``` html
<div class="half">
  <div>	
    <img src="http://placehold.it/600x300.jpg" alt="">
    <p>caption 1</p>
  </div>
  <div>	
    <img src="http://placehold.it/600x300.jpg" alt="">
    <p>caption 2</p>
  </div>
  <div>	
    <img src="http://placehold.it/600x300.jpg" alt="">
    <p>caption 3</p>
  </div>
  <div>	
    <img src="http://placehold.it/600x300.jpg" alt="">
    <p>caption 4</p>
  </div>
</div>
```

``` css
.half div {
  float: left;
  width: 50%;
  padding-right: 10px;
}
```

Which gives you this crude thing.

![gallery](https://cloud.githubusercontent.com/assets/1376749/12719170/8666bfaa-c8c1-11e5-8000-cc141ef3344d.jpg)

Obviously you'll need more styling. Not sure how many images you wanted next together but you could just change the width percentage to fit that (2 = 50%, 3 = 33.3333%, etc).

**Comment by mmistakes** [comment]
Also not sure if a `<figure>` element can have multiple `<figcaption>`s or not... I haven't checked the spec. That's why I went with the `<div>` instead, but semantically figure/figcaption is probably the way to go.

This [Stack Overflow thread](http://stackoverflow.com/questions/26913640/html5-multiple-figcaption-inside-figure) seems to suggest you can with something like this:

``` html
<figure role="group">

    <figure role="group">
    <img src="picture1.jpg" alt="Description of picture 1">
    <figcaption>Caption for Picture 1</figcaption>
    </figure>

    <figure role="group">
    <img src="picture2.jpg" alt="Description of picture 2">
    <figcaption>Caption for Picture 2</figcaption>
    </figure>

</figure>
```

**Comment by saatvikshah1994** [comment]
The `<div class="half">` method works perfectly! Thanks.
I tried the `<figure role="group">` but it isnt working as expected, so I just used the former method.
Thanks for the help :+1:
