### ISSUE TITLE
Importing bootstrap without affecting the menu options

### ISSUE THREAD

**Issue by saatvikshah1994** [mmistakes/hpstr-jekyll-theme#134]
I wanted to create a new customized page using bootstrap which is why I added the following line:
```
layout: post-index
title: Portfolio
description: 
tags: [about]
comments: false
image:
  feature: websitebg1.jpg
---

<!--this line-->
<link href="./assets/css/bootstrap.min.css" rel="stylesheet">
```

This overwrites most of the css which you had defined, allowing me to style the page correspondingly.
However the problem is that I am losing the style of the menu, which originally appeared as
![orig](https://cloud.githubusercontent.com/assets/6854735/12762521/892ea22a-ca15-11e5-8242-038d3041c97d.png)
And is now appearing as
![new](https://cloud.githubusercontent.com/assets/6854735/12762537/96a00994-ca15-11e5-82e3-481ee15fd50a.png)

I've never worked with scss, and was thus hoping if you could help me with this bit. Thanks again !

**Comment by mmistakes** [comment]
My theme isn't Bootstrap compatible so unless you want to restyle it completely using that it could be really hard to piece it together with my current styles. I'm guessing there are style conflicts between Bootstrap and my theme due to common `.class` and `#id` names. Which is why the menu doesn't look right.

Maybe you can just pull in the bits of Bootstrap you want, taking care to avoid any class name conflicts. Anything else is out of scope of what the theme was designed to do.

**Comment by saatvikshah1994** [comment]
Again, although a bit unrelated, since the recent Github-Pages update, Im unable to use Named HTML files as described here http://jekyllrb.com/docs/pages/. Why is this?

**Comment by mmistakes** [comment]
No idea. File an issue upstream on the Jekyll repo. There were some
permalink related changes that might have messed with your current workflow.

**Comment by saatvikshah1994** [comment]
Ok thanks it was the permalink problem.
Thanks again! 
I'm closing this issue.
