### ISSUE TITLE
About-menu shows vertical scrollbar with 5 or more contact link items

### ISSUE THREAD

**Issue by teelahti** [mmistakes/hpstr-jekyll-theme#14]
When there are 4 or less items in the about-menu it works flawlessly. If there are 5 or more, it shows a vertical scrollbar. This scrollbar was not visible on [January 15th of 2014 version](https://github.com/mmistakes/hpstr-jekyll-theme/commit/6f09306ffe89deb5ba29ebcd3b6160468bb6492c); one of the commits since then has changed the menu height. Reason for the current behavior is [at main.css](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/assets/css/main.css#L1575)

    @media only screen and (min-width: 48em) {
        .dl-menuwrapper .dl-menu {
            max-height: 650px;

![image](https://f.cloud.github.com/assets/581565/2313759/51590e8e-a30d-11e3-89f3-357fbf09ba84.png)

Tested and reproducible with Chrome 35, IE 11, and FF 28.

**Comment by djechlin** [comment]
bump...  since I'm working on this right now. Problem is the scrollbar won't scroll to the later elements. I'm not sure what's limiting the height or preventing the overflow. The scrollbar does appear and scroll a tiny bit though.

**Comment by djechlin** [comment]
http://stackoverflow.com/questions/28532058/dlmenu-scroll-does-not-allow-access-for-last-few-elements?noredirect=1#comment45379147_28532058 SO is on it

**Comment by mmistakes** [comment]
@djechlin The real problem with the nav is the fixed positioning and people trying to make the menu deeper than it was originally intended to be. If you want to solve the problem the easy way and don't care about the nav being in view all the time, you can change `.dl-menuwrapper { position: fixed; }` to `position: absolute;`.

Then you can remove the `max-height` declarations from `.dl-menu-wrapper .dl-menu` and call it a day giving you something that resembles this:

![hpstr-nav](https://cloud.githubusercontent.com/assets/1376749/6206332/80358a1a-b555-11e4-9fb7-ce08bee03ef1.gif)

Otherwise you can play around with the `max-height` values until you get one that works for you. I designed the theme to support popular window sizes. In my use cases none of them fell below 600px high. If you have a short window size then the menu will fall outside of the viewport which explains why you some of the list items or unscrollable.

If you want to get fancy you can use media queries that filter on height in addition to width to cover your bases.

**Comment by mmistakes** [comment]
Possible fix.

Add this to `.dl-menuwrapper .dl-menu`

```scss
.dl-menu-wrapper .dl-menu {
  overflow-y: auto;
  overflow-x: hidden;
  height: 80%;
}
```

and remove `max-height: 600px` and `650px`.

Which should show only scrollbars when content extends beyond the container's height.

![nav-scroll](https://cloud.githubusercontent.com/assets/1376749/16394362/cad29a08-3c82-11e6-9e01-9f7badf7161d.jpg)
