### ISSUE TITLE
From Page 2 back to Page 1

### ISSUE THREAD

**Issue by gidegirona** [mmistakes/hpstr-jekyll-theme#151]
Hi,

I've observed that when you reached page two on the blog you cannot come back to page1 by click to previous or the actual number 1. For sure You've detected this problem, do you how it can be fixed?

Thanks

**Comment by mmistakes** [comment]
It works just fine, check the demo site. The issue is you probably didn't specify a `url: ` in your `_config.yml` when testing locally. If you do that the previous link will appear not to work. The same if you try to click the site name link in the header.

Set it as `url: http://localhost:4000` when testing locally or your domain when pushing to production and it will just fine.
