### ISSUE TITLE
Stackexchange redirects to example.com/username

### ISSUE THREAD

**Issue by danpolanco** [mmistakes/hpstr-jekyll-theme#60]
This might be a problem with my setup, but it's pretty close to stock setup. Try clicking on the stack exchange link here: http://blazingaddles.com/

It doesn't redirect to stack exchange. Instead, it tries to redirect to http://blazingaddles.com/dlpolanco

**Comment by wordsforthewise** [comment]
Hmm, it's not showing up for me even though I have my stackexchange link on there...http://wordsforthewise.github.io/

I also noticed there's an extra link at the bottom of the 'about' nav section...possibly related?
![image](https://cloud.githubusercontent.com/assets/10804060/9866277/39212d7e-5b26-11e5-88f1-d67d82b07974.png)

**Comment by mmistakes** [comment]
@wordsforthewise You still have trouble getting the link to show? I see it just fine on your site. You may have to scroll some depending on the screen size, length of your bio, amount of links, etc.

![stack](https://cloud.githubusercontent.com/assets/1376749/9882501/eaa64c56-5ba2-11e5-8512-d4031c25ccd4.jpg)

**Comment by wordsforthewise** [comment]
Hmm, yeah if I zoom to 90% I can see it, at 100% I can't.

**Comment by mmistakes** [comment]
You can play around with the CSS on the sidebar menu to adjust the height.
I'd recommend taking out the "Learn More" button to save a bunch of space.
That or remove some links. I never really designed it to have more than 1-2
links.

**Comment by wordsforthewise** [comment]
I see. Thanks

**Comment by mmistakes** [comment]
Also if you only care about modern browsers seeing your site in the best possible light you can alter 2 lines of CSS in `/_sass/_dl-menu.scss`. Instead of setting max-height at [600px](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/_sass/_dl-menu.scss#L129) and [650px](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/_sass/_dl-menu.scss#L141) you can make them something like 90vh. This will make the menu fill 90% of the [viewport height](http://caniuse.com/#feat=viewport-units) and fix any issues with it appearing off screen.

There's been a few pull-requests in the past trying to fix this issue but everyone's content needs are different. Everytime I merge in a fix it seems to break in another use case. I think it's just one of those things you need to get your hands dirty with and customize the styling to fit your particular site.

**Comment by wordsforthewise** [comment]
Nice, the 90vh worked well. I changed all the max-heights in the sass file
(only present for the dl-menu blocks).  Thanks!
