### ISSUE TITLE
Posts not rendered in GitHub Pages

### ISSUE THREAD

**Issue by krlmlr** [mmistakes/hpstr-jekyll-theme#91]
Until now, I've been pushing my site to GitHub and let them do the rendering. After updating to 1.4.0, no styling is applied to the posts anymore, e.g. http://krlmlr.github.io/from-zero-to-tested-in-five-minutes/ .

Do I have to render my pages myself? Thanks.

**Comment by vbrard** [comment]
What happens when you render locally with
`````bash
$ bundle exec jekyll serve
`````

Could it be my commit (837e805) that causes this? It's a one liner, so maybe try to locally revert this commit and push to your repo to see if it helps render your post.

I'm not sure how the rendering is triggered on the github side though. So you may need to create a dummy new post to see if the above works.

Hope this helps.

**Comment by krlmlr** [comment]
Local behavior is just the same, except for encoding issues:

![screenshot from 2015-04-15 00 59 06](https://cloud.githubusercontent.com/assets/1741643/7149172/a3a24316-e30a-11e4-82b7-32c10d0356d2.png)

Reverting the commit you mentioned didn't help neither locally nor on gh-pages.

**Comment by krlmlr** [comment]
Added you as a collab. I just don't want the drafts to float around the web, that's the reason for privacy...

**Comment by mmistakes** [comment]
Hard to tell what's going on here without seeing the source, but I would guess it's something screwy with the YAML in your posts. Are you telling them the right `layout:` to use? Also time to upgrade your version of Jekyll I think, 1.4 is super old. There's probably a breaking change between 1.4 and whatever version GitHub Pages is using now that broke your site.

Update the Jekyll gem to 2.5.3 and see if your site builds locally. You'll have an easier time pinpointing any errors there since GH Pages doesn't always tell you what's wrong when you push commits.

**Comment by mmistakes** [comment]
@vbrard I doubt it has anything to do with your commit. These posts are outputting without a layout. If you look at the HTML source it's just the post without any of the rest of the markup needed to wrap it and load in any stylesheets/Javascript/etc.

**Comment by krlmlr** [comment]
@mmistakes: Thanks, added you too as a collab. 1.4 = the version of HPSTR, my local Jekyll is up to date.

**Comment by mmistakes** [comment]
Weird I'm out of ideas. I just downloaded your repo and it built fine locally. I didn't see anything that might be causing problems either. You could try reverting the commits from 1.4 but I seriously doubt that's the problem since the demo site is working fine on GitHub Pages with it.

The only other thing I noticed were extra spaces here and there in your `_config.yml`. In my experience YAML is really fragile an extra space or tab can really screw things up. I didn't do a deep dive into all of your files but are you sure you didn't change anything else other than the small theme changes? GH is barfing on something you're pushing.

I did see some errors for `layout: nil` in atom.xml and sitemap.xml that should be changed to `layout: null`, but that shouldn't effect your posts.

**Comment by krlmlr** [comment]
The main page renders fine. It's just when I click on a post (e.g., the first one). Does this work for you?

I have merged 1.4.0 via `git merge -X theirs`, I forked probably two years ago so there were many updates.

**Comment by krlmlr** [comment]
I've tested with `jekyll serve` instead of `bundle exec jekyll serve`. Does this make a difference?

**Comment by mmistakes** [comment]
Figured it out. It's not the theme, its the YAML Front Matter in your latest post.

```
---
layout: post
title: "From zero to tested in five minutes"
description: "Set up testing of R packages with GitHub and wercker"
category: 
tags: [Git] [R]
comments: true
---
```

Check out what you have for `tags:`. It should be `tags: [Git, R]`. Those extra brackets are blowing things up.

**Comment by krlmlr** [comment]
Thanks a lot. http://iwastesomuchtime.com/on/?i=8076 applies here.

Is there a way to troubleshoot issues like this? I've seen no suspicious output from Jekyll.

**Comment by mmistakes** [comment]
Not sure. There might be a YAML linter for Sublime Text (or whatever editor you're using) that would notify you of such errors. I just [ran it through this](http://www.yamllint.com/) and it instantly found the problem.
